[pytest]
#markers标记命名主要用于项目中所有测试用例调用，编写单接口或几个接口调试时可以自行标记，但是不可与markers中重复
markers =
    api: 标记接口测试用例
    smoke: 冒烟测试用例
    order: 下单场景测试
    login: 用户登录场景测试
    scenario:用户功能使用场景测试

filterwarnings =
    ignore::UserWarning
    ignore::DeprecationWarning
    